dist: trusty
sudo: required
language: r
latex: true
cache: packages

r:
 - devel
 - release
 - oldrel

repos:
  CRAN: https://cloud.r-project.org

r_packages:
  - Rcpp
  - tokenizers.bpe
  
r_github_packages:
  - bnosac/word2vec

warnings_are_errors: true

script:
  - R CMD INSTALL ../sentencepiece
  - R CMD build .
  - R CMD check --as-cran --no-manual --no-tests --run-donttest *tar.gz
  - R CMD check --as-cran --no-manual *tar.gz

after_success:
  - find . -name *.Rout | xargs cat

after_failure:
  - find . -name *.Rout | xargs cat

